name: Test
on:
  pull_request:
    branches:
      - develop
      - master
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  build-test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6.x'

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          virtualenvs-create: true

      - name: Build and Test
        run: |
          poetry install
          poetry run pytest
          poetry build

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
